# Generated by Django 3.1.5 on 2021-01-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20210110_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='house_no',
            new_name='number',
        ),
    ]
