# Generated by Django 3.1.5 on 2021-01-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_auto_20210110_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
