# Generated by Django 3.1.5 on 2021-01-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='number',
            new_name='house_no',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='code',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='house_no',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='userimg.png', null=True, upload_to='customer_pic'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
