# Generated by Django 3.1.5 on 2021-01-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_auto_20210110_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pin',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='house_no',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='house_no',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
