# Generated by Django 3.1.5 on 2021-01-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_auto_20210110_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
