# Generated by Django 3.1.5 on 2021-01-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_auto_20210110_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
