# Generated by Django 3.1.5 on 2021-01-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_remove_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pin',
        ),
    ]
