# Generated by Django 3.1.5 on 2021-01-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_remove_order_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='number',
            new_name='house_no',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='house_no',
        ),
    ]
