# Generated by Django 3.1.5 on 2021-01-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_auto_20210114_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='code',
            new_name='pin',
        ),
    ]
