# Generated by Django 3.1.5 on 2021-01-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0013_auto_20210114_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Złożone', 'Złożone'), ('Potwierdzone', 'Potwierdzone'), ('W przygotowaniu', 'W przygotowaniu'), ('Wsyłane', 'Wsyłane'), ('Dostarczone', 'Dostarczone'), ('Anulowane', 'Anulowane')], default='Placed', max_length=20),
        ),
    ]
