# Generated by Django 3.1.5 on 2021-01-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0014_auto_20210114_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
